version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nextjs-tesing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
